### ISSUE TITLE
Override SoapClient

### ISSUE THREAD

**Issue by sanchobouillant** [PaylineByMonext/payline-php-sdk#10]
Is there a way to easily override the SoapClient used by the SDK ?

`
$client = new SoapClient(dirname(__FILE__) . '/' . PaylineSDK::WSDL, $this->soapclient_options);
$client->__setLocation($this->webServicesEndpoint . $PaylineAPI);
`

I need to use my own SoapClient connector.

Can you concider to a setClient(SoapClient $client) to the SDK ?

**Comment by llaville** [comment]
Hello @sanchobouillant. Perharps my contribution will help you. This feature is missing in Payline-SDK, and I hope Monext will add it soon

**Comment by CharlelieBouvier** [comment]
Done in V4.55.3, thanks to @llaville
