### ISSUE TITLE
[SDK 4.65.1 +] amount is mandatory, but do not accept 0 value

### ISSUE THREAD

**Issue by fabienfeatOF** [PaylineByMonext/payline-php-sdk#101]
Hello !
According to [the documentation](https://docs.monext.fr/display/DT/Historique+de+version+de+l%27API) the amount field inOrder and Payment objects is mandatory. It's ok, I can understand that. But...

![image](https://github.com/PaylineByMonext/payline-php-sdk/assets/131149162/e388920e-61ce-48bd-8c76-af67762390d8)

Our problem is that for DSP2, we need to send amount of 0€. By the way, the sdk create a soap object with null value and not 0, then the api refuse to get this amount.
I have seen in sdk code (\Payline\SoapVarFactory::userDataIsNotEmpty) that when it create the object, the empty() php function is used. But for php empty(0) = true, so the final value is null.

How could we do to send 0€ amount ?

Thanks

**Comment by thomasmonext** [comment]
Will be fix in #102

**Comment by thomasmonext** [comment]
Fixed
