### ISSUE TITLE
Update Payline kit

### ISSUE THREAD

**Issue by nicomollet** [PaylineByMonext/payline-php-sdk#2]
Hello,

The Payline kit has been updated.
Can you please update to the latest version?
https://support.payline.com/hc/fr/articles/220595087-Nouvelles-fonctionnalit%C3%A9s-Payline-4-47
Thank you
Nico

**Comment by PaylineGitHub** [comment]
This document is a pre-release note.
Payline 4.47 will be deployed on June 15 in test environement, and July 6 in production environment.
PHP kit for 4.47 will be released before July 6.

**Comment by PaylineGitHub** [comment]
PHP SDK 4.47 is released
