### ISSUE TITLE
SDK is broken since 4.52

### ISSUE THREAD

**Issue by jcambien** [PaylineByMonext/payline-php-sdk#22]
Greetings,

We've updated our production to 4.52 and we're touched by the cast warning recently introduced in `PaylineSDK`. 
Actually, any call to the API won't work until we manually fix the cast, that mean any payment or wallet creation wouldn't lead to success and it's really penalizing our production.
It seems it has been fixed into [this commit](https://github.com/PaylineByMonext/payline-php-sdk/commit/c4532ec22a8ff225771d4b70862afc255141cb77) but no release has been made since.

Any information to give ?

**Comment by PaylineGitHub** [comment]
master is up to date, we'll publish a new release this week

**Comment by nicogodon** [comment]
Hi,

Be careful in some method we have parameter type as array but in **formatRequest** some varibles are set to **null** and not **empty array** ex (owner, ownerAddress...)

**Comment by PaylineGitHub** [comment]
got it, I've already fixed owner and ownerAddress on my local version, I'll commit soon

**Comment by PaylineGitHub** [comment]
Done, release 4.52.1 is published
