### ISSUE TITLE
using "semver" for versionning number

### ISSUE THREAD

**Issue by ColonelMoutarde** [PaylineByMonext/payline-php-sdk#24]
[http://semver.org/](http://semver.org/)
in french:
[http://putaindecode.io/fr/articles/semver/](http://putaindecode.io/fr/articles/semver/)

**Comment by ColonelMoutarde** [comment]
please see semver manual. 
1 digit : breaking change
2nd digit: functionnality
3 digit : fix bug

in your case, 4.56.1 is good.

**Comment by CharlelieBouvier** [comment]
Yes I've seen it, but Payline release are this way
Major : 4.57, 4.58, ...
Minor : 4.57.1, 4.57.1 ...
Payline V5 is not a subject for now.

We would like not to disconnect Payline's version from the kit.
So, does it suits you if we add a 0 for our major version in the kit.
Major 4.57, kit => 4.57.0

**Comment by ColonelMoutarde** [comment]
Minor version it's just for adding functionnality. 
If you remove an function i'ts an breaking change. 
In your case, 4.56.1 is good. 0 it's only if you change to minor or major. 
Samples, see this repo from packagist.
https://packagist.org/packages/calendar/icsfile

**Comment by CharlelieBouvier** [comment]
We never remove functions.
You said 4.56 is not Ok, then 4.56.0 is. I'll do this
