### ISSUE TITLE
mcrypt is deprecated 

### ISSUE THREAD

**Issue by AntoineLemaire** [PaylineByMonext/payline-php-sdk#29]
mcrypt is DEPRECATED in PHP 7.1.0, and REMOVED in PHP 7.2.0

http://php.net/manual/en/intro.mcrypt.php

used in `PaylineSDK::getEncrypt()` and `PaylineSDK::getDecrypt()`

**Comment by CharlelieBouvier** [comment]
Fixed by 998310de7c2ad24c4a08eaaeed8d4bc23645ae7c

**Comment by CharlelieBouvier** [comment]
Fixed by 998310de7c2ad24c4a08eaaeed8d4bc23645ae7c
