### ISSUE TITLE
error code 02305 : Invalid field format : OrderDetail Ref : Max length 50 characters

### ISSUE THREAD

**Issue by trileude** [PaylineByMonext/payline-php-sdk#3]
Hi,
I use your sdk with Payline woocommerce plugin and I have the following error for some products : error code 02305 : Invalid field format : OrderDetail Ref : Max length 50 characters.
How can I see what is send in the OrderDetail to correct the product ?

Thanks,

**Comment by PaylineGitHub** [comment]
Hello,

In our wooCommerce plugin, order details are sent by woocommerce-payline/class-wc-gateway-payline.php, starting at line 620.
Just comment the foreach loop, or truncate $item['name'] to 50 characters/
