### ISSUE TITLE
mcrypt

### ISSUE THREAD

**Issue by ColonelMoutarde** [PaylineByMonext/payline-php-sdk#33]
Attention, mcrypt library was deprecated in php7 and removed in php7.2

**Comment by CharlelieBouvier** [comment]
You could use this : https://stackoverflow.com/questions/48275494/issue-in-installing-php7-2-mcrypt

I will look for another solution

**Comment by ColonelMoutarde** [comment]
The reason for remove mcrypt.
https://wiki.php.net/rfc/mcrypt-viking-funeral 

"La raison en est simple : elle n’est plus maintenue depuis 8 ans et comporte de nombreuses failles de sécurité. Et surtout, son chiffrage est facilement cassable en le comparant aux fonctions actuelles. En plu,s cette fonction est signalée comme Deprecated (déconseillée) depuis la version 7.1.0.

Donc si vous l’utilisez encore dans vos projets, migrez vers une autre fonction de cryptage moderne car si vous mettez à jour votre PHP, cela risque de coincer."

**Comment by CharlelieBouvier** [comment]
Fixed by 998310de7c2ad24c4a08eaaeed8d4bc23645ae7c
