### ISSUE TITLE
openssl_encrypt error

### ISSUE THREAD

**Issue by AntoineLemaire** [PaylineByMonext/payline-php-sdk#36]
With the remove of mcrypt (https://github.com/PaylineByMonext/payline-php-sdk/pull/35), I can't use the encrypt anymore : 

	$aes256Key   = hash('SHA256', $accessKey, true);
	$messageUtf8 = utf8_encode($merchandId.';'.$orderRef.';'.$contractNumber);

	$encrypted = $paylineSDK->getEncrypt($messageUtf8, $aes256Key);

give me empty string because `openssl_encrypt` return `false` with an error:

        if (false === $encrypted) {
            echo openssl_error_string();
            die;
        }

`0607F08A:digital envelope routines:EVP_EncryptFinal_ex:data not multiple of block length`

**Comment by CharlelieBouvier** [comment]
Hello,

Could you provide a code snippet and show how you call the function please?
Could you provide some environment info?

Then I'll look into it. It works in PHP 5.6 and 7.1.6 with WAMP

**Comment by AntoineLemaire** [comment]
Here the code I use for test:
```
<?php

require_once "vendor/autoload.php";

use Payline\PaylineSDK;

$merchandId = '123456789123456';
$accessKey = '59FyHSzJbeu74dKNBC';
$orderRef = '3-2018-09006649';
$contractNumber = '1234567';

$paylineSDK = new PaylineSDK($merchandId, $accessKey,null,null, '', '', 0);

$aes256Key   = hash('SHA256', $accessKey, true);
$messageUtf8 = utf8_encode($merchandId.';'.$orderRef.';'.$contractNumber);

$encrypted = $paylineSDK->getEncrypt($messageUtf8, $aes256Key);

if (false === $encrypted) {
    echo openssl_error_string();
    die;
}

var_dump('finish');
```

Php 
```
PHP 7.2.11-2+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Oct 15 2018 11:40:35) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.11-2+ubuntu18.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
    with blackfire v1.23.1~linux-x64-non_zts72, https://blackfire.io, by Blackfire

```

Linux version:
```
18.04.1 LTS
Linux version 4.15.0-38-generic (buildd@lcy01-amd64-023) (gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3)) #41-Ubuntu SMP Wed Oct 10 10:59:38 UTC 2018
```

**Comment by AntoineLemaire** [comment]
If I create a `index.php` with my code inside `PaylineByMonext/payline-php-sdk` it's works well, but not on my projet.

It should be something in my composer.json, i'll try differents things monday

**Comment by AntoineLemaire** [comment]
I still have issues, whatever php version. I seams that's because of your OPENSSL_ZERO_PADDING option.

https://stackoverflow.com/a/41677002/2409987

If you pad your message before try to encrypted it, it's working:

```
if (strlen($message_padded) % 16) {
    $message_padded = str_pad($message_padded,
        strlen($message_padded) + 16 - strlen($message_padded) % 8, "\0");
}
```

https://github.com/AntoineLemaire/payline-php-sdk/commit/cb048866e38250c03e19c28d701af6682c2d55b8

**Comment by CharlelieBouvier** [comment]
Hello, make a PR please, and I'll try it :)
