### ISSUE TITLE
Erreur XXXXX

### ISSUE THREAD

**Issue by marinemattei** [PaylineByMonext/payline-php-sdk#43]
Le commerçant VPG rencontre des erreurs de lecture des codes retour des transactions réalisées. 

En effet, une transaction acceptée sur le CA est affichée avec le code XXXXX sur le SDK PHP.

Voici le message affiché : 
( {"result":{"code":"XXXXX","longMessage":"Undefined index: id","shortMessage":"Undefined index: id","partnerCode":null,"partnerCodeLabel":null}}) 

La version utilisée est la 4.55.

**Comment by CharlelieBouvier** [comment]
Bonjour, il nous faut un environnement et des id transactions dans une PAYLANO stp
