### ISSUE TITLE
Procédure de mise à jour

### ISSUE THREAD

**Issue by 2803media** [PaylineByMonext/payline-php-sdk#45]
Bonjour,

Dans la doc aucune référence à la mise à jour du SDK lorsqu'on a déjà une version live. Pouvez vous me donner cela svp avant de tout écraser et peut être planter ce qui marche ;)

Merci

**Comment by CharlelieBouvier** [comment]
Bonjour,

Il n'y a pas de breaking changes sur notre API, la version est spécifiée en entrée de l'appel. Les évolutions permettent juste d'accéder à de nouvelles versions ou de nouvelles fonctionnalités.

Vous pouvez donc mettre à jour sans problème. Si toutefois problème il y a, merci de nous en informer via une issue, et de rollback sur la version précédente.

Bien cordialement,
Charlélie

**Comment by 2803media** [comment]
Merci @CharlelieBouvier je dois tout re-télécharger et remplacer le dossier vendor et lib ou bien simplement changer le numéro dans l'appel comme par exemple:

$doWebPaymentRequest['version'] = 19;

en 

$doWebPaymentRequest['version'] = 21;

**Comment by CharlelieBouvier** [comment]
non, il ne faut pas changer la version dans l'appel si ce n'est pas nécessaire au niveau métier.

vous pouvez updater le kit via packagist ou bien télécharger et remplacer les fichiers en prenant en compte la conservation des confs (merchantId etc).

**Comment by 2803media** [comment]
Merci le fait est que je suis vraiment pas à l'aise avec ce type d'installation. Donc pour résumer un simple 
`php composer.phar update`
devrait le faire ? 

Le sdk a été initialement installé via composer!

**Comment by 2803media** [comment]
@CharlelieBouvier hello est ce que c'est la bonne procédure cf le message précédent? Je dois faire la maj pour la DSP2... merci par avance

**Comment by CharlelieBouvier** [comment]
Bonjour,

Hélas je ne suis pas expert en composer, mais je pense que la piste est la bonne. Peut-être voudrez-vous n'updater que le package Payline et pas les autres?

Une piste ici : https://stackoverflow.com/questions/16739998/how-to-update-a-single-library-with-composer

**Comment by 2803media** [comment]
quelque chose comme cela donc : 

`composer.phar require vendor/monext`
`composer.phar update vendor/monext`

?

**Comment by CharlelieBouvier** [comment]
à priori le package c'est monext/payline-sdk :
https://packagist.org/packages/monext/payline-sdk

**Comment by 2803media** [comment]
après un test 
`php composer.phar update
`
fonctionne très bien

En revanche il ne prend pas le reorderIndicator ni AddressCreateDate

```
if($reorder > 0){
  $reorderIndicator = 02;
} else {
  $reorderIndicator = 01;
}

$datecreationaccount = date("d/m/y", strtotime($date));

$doWebPaymentRequest['order']['orderExtended']['reorderIndicator'] = $reorderIndicator;
$doWebPaymentRequest['shippingAddress']['AddressCreateDate'] = $datecreationaccount;


```

**Comment by 2803media** [comment]
@CharlelieBouvier pour AddressCreateDate en fait il y a une erreur dans le doc de migration dsp2 il ne faut pas la majuscule au A addressCreateDate

En revanche le reorderIndicator ne fonctionne pas vous me confirmez cela?

Merci

**Comment by CharlelieBouvier** [comment]
De quel doc de migration dsp2 parlez-vous? Vous avez un lien svp?

- Je confirme, c'est un a et non un A.
- Le champ order extended est un champ JSON, ce n'est pas un objet mappé via un tableau
Voici la doc :
https://payline.atlassian.net/wiki/spaces/DT/pages/28901480/Object+-+order

Voici un exemple :

{
"deliveryProvider": "deliveryProvider",
"riskLevel": "3",
"giftCardAmount": "4000",
"giftCardCurrency": "978",
"giftCardCount": "2",
"reorderIndicator": "01"
}

**Comment by 2803media** [comment]
Ci joint le lien avec l'erreur pour addressCreateDate : https://payline.atlassian.net/wiki/spaces/DT/pages/28901534/Object+-+address

Je fais un test pour le json de order extended

**Comment by CharlelieBouvier** [comment]
Très bien merci pour le lien :)

**Comment by 2803media** [comment]
pour le reorderindicator je viens de tester cela:

if($reorder > 0){
  $reorderIndicator = "02";
} else {
  $reorderIndicator = "01";
}

$arrayreorder = array("reorderIndicator" => $reorderIndicator);
$doWebPaymentRequest['order']['orderExtended'] = json_encode($arrayreorder);

Mais le résultat n'est pas comme l'exemple:

<ns2:otaDestinationCountry xsi:nil="true"/>
    <ns2:bookingReference xsi:nil="true"/>
    <ns2:orderDetail xsi:nil="true"/>
    <ns2:orderExtended>{"reorderIndicator":"02"}</ns2:orderExtended>
    <ns2:orderOTA xsi:nil="true"/>
  </ns1:order>

Alors que cela devrait être:

<ns2:orderExtended>
<ns2:reorderIndicator>01</ns2::reorderIndicator>
</ns2:orderExtended>

une idée de mon erreur?

**Comment by CharlelieBouvier** [comment]
Je ne comprends pas, l'attendu c'est bien :

<ns2:orderExtended>{"reorderIndicator":"02"}</ns2:orderExtended>

**Comment by 2803media** [comment]
Dans l'exemple de la page https://payline.atlassian.net/wiki/spaces/DT/pages/1328939253/3DSv2+-+Augmenter+le+frictionless

l'attendu n'est pas 
`<ns2:orderExtended>{"reorderIndicator":"02"}</ns2:orderExtended>`

**Comment by CharlelieBouvier** [comment]
La doc est erronée, je vais demander qu'elle soit modifiée.
L'attendu est bien celui cité plus haut, désolé pour le doute :)

**Comment by 2803media** [comment]
super merci au moins la doc se corrige au fil du temps ;)

**Comment by CharlelieBouvier** [comment]
Oui merci beaucoup pour vos retours :)

**Comment by 2803media** [comment]
de rien !

dernière question le frictionless va fonctionner automatiquement ou il faut ajouter quelque chose dans le code? genre dans le champs threedsInfo?

**Comment by CharlelieBouvier** [comment]
Il y a possibilité d'indiquer une préférence via le threedsinfo.challengeInd, mais c'est une préférence, selon le risque encouru il y aura peut-être un challenge :

https://payline.atlassian.net/wiki/spaces/DT/pages/1437008540/Codes+-+ChallengeInd

**Comment by 2803media** [comment]
si je ne fais pas cela l'ajout des champs comme le reorderIndicator n'a aucun intérêt ou c'est tout de même utile c'est bien cela? Désolé j'essaie de comprendre le fonctionnement ;)

**Comment by CharlelieBouvier** [comment]
Je n'en ai aucune idée, je ne suis pas expert sur cette partie là désolé :/

Je pense que plus il y a d'info mieux c'est pour calculer le risque et avoir la meilleure expérience utilisateur possible.
