### ISSUE TITLE
3DS verifyEnrollment broken in 4.59.0

### ISSUE THREAD

**Issue by jdeniau** [PaylineByMonext/payline-php-sdk#46]
You added a lot of function calls in the `verifyEnrollment` method, but those function now requires an array as first parameter. This is a breaking change.

https://github.com/PaylineByMonext/payline-php-sdk/compare/4.55.3...4.59.0#diff-eec0d48cf2eda6e48bad70276112f445R1776-R1781

According to [your documentation](https://payline.atlassian.net/wiki/spaces/DT/pages/1421377779/Webservice+-+verifyEnrollmentRequest), only the `order` is required for version 21

**Comment by CharlelieBouvier** [comment]
Hello,

We're aware of this issue and we will fix it very soon.

Thank you for reporting it

**Comment by CharlelieBouvier** [comment]
It should now be ok, please let me know

**Comment by jdeniau** [comment]
If I remember correctly, it's the same for `buyer`, `submerchand` and `threeDSInfo` methods ?

As a matter of fact, you may replace `$array['order'] != null` by `!empty($array['order'])` to avoid notice being triggered if the 'order' key does not exist.

**Comment by CharlelieBouvier** [comment]
Can you please review this PR and let me know?
https://github.com/PaylineByMonext/payline-php-sdk/pull/48
