### ISSUE TITLE
Webpayment: Une erreur est survenue, veuillez réessayer

### ISSUE THREAD

**Issue by DayBr3ak** [PaylineByMonext/payline-php-sdk#53]
Bonjour, depuis peu la page de redirection de doWebPayment ne marche plus 
(https://webpayment.payline.com/v2/?token=1IdSqIykTRKrbU2796151573656127505)

La page web affiche "Une erreur est survenue, veuillez réessayer."

Le serveur renvoi Erreur 500 sur l'URL (en ajax)

https://payment.payline.com/services/token/1IdSqIykTRKrbU2796151573656127505/state/current

Est-il possible d'avoir un message d'erreur plus détaillé

**Comment by CharlelieBouvier** [comment]
Bonjour,

Le problème n'est pas lié au kit à priori, pourriez-vous ouvrir un ticket auprès du support svp?

**Comment by DayBr3ak** [comment]
Bonjour, j'ai trouvé le problème.

Il s'agissait du "returnURL" qui avait un charactère "|". Ça fonctionnait avant.
J'ai changé ça avec un `rawurlencode`.

Cordialement.

**Comment by CharlelieBouvier** [comment]
Très bien merci pour votre retour
