### ISSUE TITLE
account verification request

### ISSUE THREAD

**Issue by CyrielMonext** [PaylineByMonext/payline-php-sdk#54]
It is impossible to make an information request.
By setting the amount to null and the action code to 108, the answer is: Invalid field format: Payment Currency: Must be numeric(3), ex: 978
When removing the line the return is the same.
To fix the problem, delete in the 4.59 wsdl line 1942 the "nillable="true""

**Comment by CharlelieBouvier** [comment]
This problem is on the Payline side, not the php sdk
