### ISSUE TITLE
Format différent champ "cardList.cards" sur la version 4.59 du kit PHP

### ISSUE THREAD

**Issue by JuPayline** [PaylineByMonext/payline-php-sdk#55]
Nous rencontrons un erreur sur le format du retour du service de getCards. La valeur du champs cardList.cards était auparavant un tableau (de tableau associatif), c'est désormais un tableau associatif.

Cela n'est pas conforme à la documentation: https://payline.atlassian.net/wiki/spaces/DT/pages/1452180199/Webservice+-+getCardsResponse

Ci-joint un exemple de réponse reçu sur la version 4.49 et un exemple de réponse sur la version 4.59
[new_response.txt](https://github.com/PaylineByMonext/payline-php-sdk/files/3973767/new_response.txt)
[old_response.txt](https://github.com/PaylineByMonext/payline-php-sdk/files/3973768/old_response.txt)

**Comment by CharlelieBouvier** [comment]
Le WSDL indique que la new response est correcte et la old response incorrecte. Je n'explique pas ce changement par contre.

Il faut voir avec le marchand s'il peut faire un changement.

**Comment by fionasdv** [comment]
Bonjour,
Je rencontre le même problème suite à une mise à jour du SDK : 4.53 -> 4.59
Un test sur le type Countable a été ajouté dans la fonction responseToArray et modifie la construction de la réponse dans le cas d'un résultat avec 1 seul élément (en réponse à l'issue #30).
Pourquoi ne pas ajouter l'option SOAP_SINGLE_ELEMENT_ARRAYS à la création du SoapClient ?

**Comment by CharlelieBouvier** [comment]
Bonjour,

Je réouvre l'issue pour analyser ça, merci pour votre retour

**Comment by thomasmonext** [comment]
Résolu
