### ISSUE TITLE
PaylineSDK::updateWallet & formatRequest

### ISSUE THREAD

**Issue by AntoineLemaire** [PaylineByMonext/payline-php-sdk#57]
Is that normal that function `updateWallet` does not use

    $this->formatRequest($array);

but createWallet does?

If `$array['merchantAuthentication']` is not defined, it broke because `PaylineSDK::buyer()` method need 4th argument to be an array and not null. `formatRequest` is adding `merchantAuthentication` as empty array if not exists

![image](https://user-images.githubusercontent.com/2025537/72142247-8bb08800-3394-11ea-9058-d0972134d36c.png)

**Comment by CharlelieBouvier** [comment]
Hello,

It seems it's not normal, I'll check this asap.

Thank you for reporting it.
