### ISSUE TITLE
challengeWindowSize missing from the SDK

### ISSUE THREAD

**Issue by tdumoulin** [PaylineByMonext/payline-php-sdk#58]
Hello,

In the verifyEnrollment call, in threeDSInfo object, the field challengeWindowSize can be fill (cf doc: https://payline.atlassian.net/wiki/spaces/DT/pages/1437303489/Object+-+threeDSInfo)
but the field doesn't appear in v4.59.wsdl and not in ThreeDSInfo.php neither

**Comment by thomasmonext** [comment]
Résolu
