### ISSUE TITLE
Problem on PHP Version 7.0.5

### ISSUE THREAD

**Issue by neopheus** [PaylineByMonext/payline-php-sdk#6]
Hi,

I'm migrating to php 7
But I encounter difficulties with Paylinee

indeed with PHP Version 5.x I have no problem
However with PHP 7 (I tried with PHP 7.0.5) all my transactions have an exception :

> Exception : Function ("doAuthorization") is not a valid method for this service

Thank you

**Comment by jpclair** [comment]
Can't reproduce your issue with a similar environment and with the doWebPayment feed:
```
○ → php -v
PHP 7.0.13 (cli) (built: Nov 15 2016 23:52:36) ( NTS )
```

Code:
```
...
$doWebPaymentResponse = $paylineSDK->doWebPayment($doWebPaymentRequest);
```

The response from Payline is conform, and I have no exceptions.

@neopheus can you share an example?
