### ISSUE TITLE
[\Payline\PaylineSDK::doReAuthorization] 'order' parameter is mandatory

### ISSUE THREAD

**Issue by Omegadela** [PaylineByMonext/payline-php-sdk#60]
```
TypeError: Argument 1 passed to Payline\PaylineSDK::order() must be of the type array, null given, called in /var/www/html/vendor/monext/payline-sdk/src/Payline/PaylineSDK.php on line 1472
```

According to [Monext documentation](https://docs.monext.fr/display/DT/Webservice+-+doReAuthorizationRequest), the 'order' details are not mandatory for a doReAuthorizationRequest  

Calling the service with an empty 'order' array returns : 
```
ERROR. Code 02305 : Invalid field format : Order Amount : Must be numeric(12), ex : 15078
```

Is there a workaround for reAuthorizing a transaction without order details ?

**Comment by thomasmonext** [comment]
Résolu
