### ISSUE TITLE
Support for PHP 7.4

### ISSUE THREAD

**Issue by geneowak** [PaylineByMonext/payline-php-sdk#62]
Am running version `4.59.5` and I get this error when am running on php7.4
```json
file: "/monext/payline-sdk/src/Payline/PaylineSDK.php"
line: 2472
message: "array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead"
```

Is there a version that supports php7.4?

**Comment by smknstd** [comment]
any news on this one ?

**Comment by geneowak** [comment]
@smknstd you can add this line before calling payline

```php
// Report all errors except E_DEPRECATED as payline doesn't yet support php7.4
error_reporting(E_ALL & ~E_DEPRECATED);
```
I would suggest adding it only in the method(s) where the payline SDK is called so that the other possible errors are still reported and fixed...

**Comment by smknstd** [comment]
Thanx for your suggestion, but far from ideal. I just made a PR to fix deprecated `array_key_exists()`: https://github.com/PaylineByMonext/payline-php-sdk/pull/64

Just noticed the sdk has no unit tests at all !?

**Comment by geneowak** [comment]
@smknstd, true but I think if it is isolated in one method that calls the endpoint then there's no harm and one can go with it while we wait for them to fix it... It's better than having to downgrade the php version on a server and in my case I am using a vital package that have php 7.4 as the min php version so downgrading isn't an option.

**Comment by neopheus** [comment]
Support Php 7.4 with new PR : https://github.com/PaylineByMonext/payline-php-sdk/pull/66
