### ISSUE TITLE
4.69 version: Too few arguments to function Payline\PaylineSDK::buildSoapObject(), 2 passed and exactly 3 expected

### ISSUE THREAD

**Issue by amarmain** [PaylineByMonext/payline-php-sdk#82]
Too few arguments to function Payline\PaylineSDK::buildSoapObject(), 2 passed in

(...)/vendor/monext/payline-sdk/src/Payline/PaylineSDK.php on line 1586 and exactly 3 expected

**Comment by oreaweb** [comment]
> Too few arguments to function Payline\PaylineSDK::buildSoapObject(), 2 passed in
> 
> (...)/vendor/monext/payline-sdk/src/Payline/PaylineSDK.php on line 1586 and exactly 3 expected

Dans le fichier paylineSDK.php, ligne 1586, il faut écrire :

$this->privateData[] = $this->buildSoapObject($array, new PrivateData(), self::SOAP_PRIVATE_DATA);

au lieu de :

$this->privateData[] = $this->buildSoapObject($array, new PrivateData());

**Comment by thomasmonext** [comment]
fix in => https://github.com/PaylineByMonext/payline-php-sdk/releases/tag/4.69-RC2

**Comment by mWardi** [comment]
RC is for Release Candidate.  Tagging RC after the release of 4.69 does not make sense.
This issue is breaking for the release 4.69. 
Can you please change the tag to something more appropriate (4.69.1 maybe) for better integration with composer, and easier dependencies management,
