### ISSUE TITLE
Add Support for Monolog V3

### ISSUE THREAD

**Issue by k3dsarl** [PaylineByMonext/payline-php-sdk#95]
Your library forces installation of monolog v2.
Can you please installation of monolog v3?

Thank you

**Comment by smknstd** [comment]
+1 . This package prevents me to upgarde to Laravel version 10 right now :( https://laravel.com/docs/10.x/upgrade#monolog-3

**Comment by polinome** [comment]
here's a pull request https://github.com/PaylineByMonext/payline-php-sdk/pull/98

**Comment by SODIKART** [comment]
+1 Laravel version >= 10

**Comment by thomasmonext** [comment]
Fixed
