### ISSUE TITLE
Warning on PHP8.2

### ISSUE THREAD

**Issue by RLHommee** [PaylineByMonext/payline-php-sdk#97]
Hello,

There's a warning with PHP 8.2:
`Deprecated:  Creation of dynamic property Classes\MonextAPI: :$webServicesEndpoint is deprecated in /monext/payline-sdk/src/Payline/PaylineSDK.php on line 433` 

Is The SDK plainly compatible with PHP 8.2 ?

**Comment by thomasmonext** [comment]
Fixed
